const mongoose = require('mongoose');

const aiAnalysisSchema = new mongoose.Schema({
  franchise: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Franchise',
    required: true
  },
  franchiseName: {
    type: String,
    required: true
  },
  franchiseEmail: {
    type: String,
    required: true
  },
  uploadedDocument: {
    type: String, // URL or path to the uploaded PDF
    required: true
  },
  uploadedDocumentName: {
    type: String,
    required: true
  },
  adminResponseDocument: {
    type: String, // URL or path to the admin response PDF
    default: null
  },
  adminResponseDocumentName: {
    type: String,
    default: null
  },
  status: {
    type: String,
    enum: ['uploaded', 'processed', 'responded'],
    default: 'uploaded'
  },
  uploadedAt: {
    type: Date,
    default: Date.now
  },
  processedAt: {
    type: Date
  },
  respondedAt: {
    type: Date
  },
  adminNotes: {
    type: String
  },
  claudeAnalysisHtml: {
    type: String, // HTML analysis generated by Claude
    default: null
  },
  claudeAnalysisFileName: {
    type: String,
    default: null
  },
  analysisPrompt: {
    type: String, // Custom prompt used for analysis
    default: null
  },
  isAutoAnalyzed: {
    type: Boolean,
    default: false
  },
  claudeAnalysisStatus: {
    type: String,
    enum: ['pending', 'processing', 'completed', 'email_sent', 'failed'],
    default: 'pending'
  },
  claudeAnalysisError: {
    type: String
  },
  analyzedAt: {
    type: Date
  }
}, {
  timestamps: true
});

module.exports = mongoose.model('AIAnalysis', aiAnalysisSchema);